const handleClickReset = (event) => {
  event.preventDefault();
  const radio1 = document.querySelector('.js_radio1');
  const previewCard = document.querySelector('.js_preview__card');
  inputName.value = '';
  inputJob.value = '';
  inputEmail.value = '';
  inputTel.value = '';
  inputLinkedin.value = '';
  inputGithub.value = '';
  cardName.innerHTML = 'Nombre Apellido';
  cardJob.innerHTML = 'Front-end developer';
  designContainer.classList.remove('collapsed');
  fillContainer.classList.add('collapsed');
  shareContainer.classList.add('collapsed');
  radio1.checked = true;
  previewCard.classList.add('palette1');
  previewCard.classList.remove('palette2');
  previewCard.classList.remove('palette3');
};
resetButton.addEventListener('click', handleClickReset);
